# Generated by Django 5.1.7 on 2025-03-19 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_mentorshipsession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentorshiprequest',
            name='is_seen',
        ),
        migrations.RemoveField(
            model_name='mentorshiprequest',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='mentorshiprequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=10),
        ),
    ]
