# Generated by Django 5.1.7 on 2025-03-20 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_remove_mentorshiprequest_is_seen_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentorshipsession',
            old_name='session_date',
            new_name='scheduled_time',
        ),
        migrations.AddField(
            model_name='mentorshipsession',
            name='mentorship_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.mentorshiprequest'),
        ),
        migrations.AddField(
            model_name='mentorshipsession',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mentorshipsession',
            name='mentee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentee_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mentorshipsession',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
